### ISSUE TITLE
New Member in room is not able to see already existing members.

### ISSUE THREAD

**Issue by nitin-** [vardius/webrtc-chat#6]
Hi ,
I am a newbie to WEBRTC and I was exploring  your project. It is an awesome work, you made my life easy. Thanks!!

Please help me how can I fix this issue and can I configure this code into my ionic 3 project.

**Comment by vardius** [comment]
The best way would be to debug, if you know how to use [debugger](https://developers.google.com/web/tools/chrome-devtools/javascript/) i would recommend this way. Otherwise you can always drop some `console.log`s and check if they execute. This should give you some idea why this happens, maybe because callback is not called or for any other reasons. There is a possibility that the `peer-data` package may cause it. Either way let me know what you found out, any pull request are very welcome.
If you let me know what you found out, can do not know how to fix it I will try to help you.

**Comment by vardius** [comment]
what version of [webrtc-adapter](https://github.com/webrtc/adapter) are you using ?

in this case i suspect that this might be related to this [issue](https://github.com/webrtc/adapter/issues/622)

**Comment by nitin-** [comment]
<script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>

Still can't find the solution.

**Comment by vardius** [comment]
hmm I can see some possible reasons:

here where the problem then will be adapter and the `ontrack` handler doesn't work
https://github.com/vardius/peer-data/blob/98d95e2a52c6300cfcbbd9d9be5f59b9b2b42944/src/app/Participant.ts#L66

or here where the dispatcher does not delegates the event to all subscribers ?
https://github.com/vardius/peer-data/blob/98d95e2a52c6300cfcbbd9d9be5f59b9b2b42944/src/app/Participant.ts#L29

or last one I can think of right now, the handler is not being registered for this participant ?
https://github.com/vardius/peer-data/blob/98d95e2a52c6300cfcbbd9d9be5f59b9b2b42944/src/app/Participant.ts#L201

**Comment by nitin-** [comment]
there is 
this.dispatchRemoteStream = function (event) {
            _this.dispatcher.dispatch('track', event);
        };
I have debugged it and  I can see that for every participants event has same id value.

**Comment by vardius** [comment]
you mean `participant` ? or `RTCTrackEvent` id if there is one ?

**Comment by nitin-** [comment]
![screenshot from 2018-05-13 18-37-13](https://user-images.githubusercontent.com/6983677/39967638-a9792bf4-56ae-11e8-8058-a53c96cceb6a.png)

Stream Id

**Comment by vardius** [comment]
can you tell me which line is this log from ?

**Comment by vardius** [comment]
I think the reason might be that `peer-data` uses `addTrack` method
can you try change this part of code (whole **if**)
https://github.com/vardius/peer-data/blob/98d95e2a52c6300cfcbbd9d9be5f59b9b2b42944/src/app/Participant.ts#L70
to simply `this.peer.addStream(stream)` instead ?

`addStream` method is deprecated but I don't thing `addTrack` works as supposed to (it is still in development) 
https://bugs.chromium.org/p/chromium/issues/detail?id=700916

**Comment by nitin-** [comment]
I have changed  

/* if (stream instanceof MediaStream) {
                                stream.getTracks().map(track => this.peer.addTrack(track, stream));
                            } */
     **this.peer.addStream(stream);**

I think there is some problem in invoking dispatchRemoteStream method As onTrack event is not getting called for the current participant

**Comment by vardius** [comment]
This has been fixed with dependencies update. https://github.com/vardius/webrtc-chat/commit/bab09ef8ff668ad213dc5cfb9ee24ae8bbdbf726
The issue was due to `track` event being dispatched before promise was resolved.
